[project]
name = "merge-pdfs"
version = "0.1.0"
description = "Adds a context menu to Windows to merge PDFs"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyinstaller>=6.12.0",
    "pymupdf>=1.25.4",
    "pywin32>=310",
]
